name: LNX build
on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    name: Linux
    env:
      CMSIS: CMSIS_5
    runs-on: ubuntu-latest
    steps:
    - name: ARM GCC setup
      uses: stopstopstop/make-action@master
      with:
        release: 8-2019-q3
    - name: Checkout
      uses: actions/checkout@v2
    - name: Resolve prerequisites
      run: make prerequisites
    - name: Build firmware
      run: make stm32f103x8
    - name: Build encrypter
      run: make crypter
    - name: Build testsuite
      run: make testsuite
    - name: Vector test
      run: build/cipher_test
